name: Workflow on label addition

on:
  pull_request_target:
    types: [labeled]  
    branches:
      - 'master'

jobs:
  e2e:
    if: contains(github.event.pull_request.labels.*.name, 'ok-to-test')
    uses: tripleo-ci/openstack-k8s-operators-ci/.github/workflows/reusable-workflow-e2e.yaml@golang-1.19
    with:
      operator_name: keystone-operator
    secrets: inherit
